{
 "title": "IOT Car Metrics",
 "description": "IOT Car metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(go_goroutines{kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "car stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "geo{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fuel level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "liquid_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tire pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pressure{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Is car moving",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "is_moving", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total mqtt event",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_mqtt_messages_received_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "go_goroutines{}" }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{}[1m])"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "go_memstats_sys_bytes{}" }
     ]
    }
   ]
  }
 ]
}